<?php

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;

function d8_training_form_alter(&$form, FormStateInterface $form_state, $form_id){
  if($form_id === 'system_site_information_settings'){
    $form['site_information']['site_key'] = [
      '#type' => 'textfield',
      '#title' => t('Site API key'),       
    ];   
    $form['actions']['submit']['#value'] = t('Submit');
    
  }
}
